<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="..\WardogsRadio.Core\WardogsRadio.Core.csproj" /><ProjectReference Include="..\WardogsRadio.Voicemeeter\WardogsRadio.Voicemeeter.csproj" /><ProjectReference Include="..\WardogsRadio.Input\WardogsRadio.Input.csproj" /><ProjectReference Include="..\WardogsRadio.Playback\WardogsRadio.Playback.csproj" /></ItemGroup></Project>
